spring.application.name=demo1

# ?? local profile??????
spring.profiles.active=local

server.port=8081
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#??entity?*mapper.xml
mybatis.type-aliases-package=com.example.demo.entity
mybatis.mapper-locations=classpath:mapper/*.xml


#mybatis.configuration.Log-impl=org.apache.ibatis.logging.log4j2.Log4j2Impl
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl